import React from 'react'
import ProposalDetailBase from '../base/ProposalDetailBase'
import CategorizedEditionChangesTable from '@/components/proposals/CategorizedEditionChangesTable'
import RaceChangesSection from '@/components/proposals/RaceChangesSection'
import ProposalJustificationsCard from '@/components/proposals/ProposalJustificationsCard'
import AgentCard from '@/components/proposals/AgentCard'
import EditionContextInfo from '@/components/proposals/EditionContextInfo'
import OrganizerSection from '@/components/proposals/edition-update/OrganizerSection'
import RacesToAddSection from '@/components/proposals/edition-update/RacesToAddSection'

interface EditionUpdateDetailProps {
  proposalId: string
}

const EditionUpdateDetail: React.FC<EditionUpdateDetailProps> = ({ proposalId }) => {
  return (
    <ProposalDetailBase
      proposalId={proposalId}
      renderMainContent={(context) => {
        const {
          consolidatedChanges,
          consolidatedRaceChanges,
          selectedChanges,
          userModifiedRaceChanges,
          handleFieldSelect,
          handleFieldModify,
          handleRaceFieldModify,
          userModifiedChanges,
          formatValue,
          formatAgentsList,
          editionTimezone,
          allPending,
          isPending,
          isEventDead,
          isEditionCanceled,
          proposal
        } = context
        
        // Séparer les champs standards des champs spéciaux
        const standardChanges = consolidatedChanges.filter(c => 
          !['organizer', 'racesToAdd'].includes(c.field)
        )
        const organizerChange = consolidatedChanges.find(c => c.field === 'organizer')
        const racesToAddChange = consolidatedChanges.find(c => c.field === 'racesToAdd')
        
        // Champs auto-générés
        const autoGeneratedFields = ['calendarStatus', 'timeZone', 'endDate']
        const realStandardChanges = standardChanges.filter(c => 
          !autoGeneratedFields.includes(c.field)
        )
        const hasRealEditionChanges = realStandardChanges.length > 0
        const hasRaceChanges = consolidatedRaceChanges.length > 0
        
        return (
          <>
            {hasRealEditionChanges && (
              <CategorizedEditionChangesTable
                title="Édition"
                changes={realStandardChanges}
                isNewEvent={false}
                selectedChanges={selectedChanges}
                onFieldSelect={handleFieldSelect}
                onFieldModify={handleFieldModify}
                userModifiedChanges={userModifiedChanges}
                formatValue={formatValue}
                formatAgentsList={formatAgentsList}
                timezone={editionTimezone}
                disabled={!allPending || isPending || isEventDead}
                isEditionCanceled={isEditionCanceled || isEventDead}
              />
            )}
            
            {organizerChange && (
              <OrganizerSection
                change={organizerChange}
                onApprove={() => {/* Single proposal - no field-specific approve */}}
                onFieldModify={handleFieldModify}
                userModifiedChanges={userModifiedChanges}
                disabled={!allPending || isPending || isEventDead}
              />
            )}
            
            {racesToAddChange && (
              <RacesToAddSection
                change={racesToAddChange}
                onApprove={() => {/* Single proposal - no field-specific approve */}}
                disabled={!allPending || isPending || isEventDead}
                proposalId={proposalId}
              />
            )}
            
            {hasRaceChanges && (
              <RaceChangesSection
                raceChanges={consolidatedRaceChanges}
                formatValue={formatValue}
                timezone={editionTimezone}
                onRaceApprove={() => {/* Single proposal - handled by approve all */}}
                onFieldModify={handleRaceFieldModify}
                userModifiedRaceChanges={userModifiedRaceChanges}
                disabled={!allPending || isPending || isEventDead}
                isEditionCanceled={isEditionCanceled || isEventDead}
              />
            )}
            
            <ProposalJustificationsCard 
              justifications={proposal.justification || []}
              confidence={proposal.confidence}
            />
          </>
        )
      }}
      renderSidebar={(context) => {
        const { 
          proposal, 
          getEditionYear, 
          selectedChanges, 
          userModifiedChanges
        } = context
        
        return (
          <>
            <AgentCard
              agent={{
                id: proposal.agent.id,
                name: proposal.agent.name,
                type: proposal.agent.type
              }}
              createdAt={proposal.createdAt}
            />
            
            {proposal && (
              <EditionContextInfo
                currentCalendarStatus={
                  userModifiedChanges['calendarStatus'] || 
                  selectedChanges['calendarStatus'] || 
                  (typeof proposal.changes.calendarStatus === 'string' 
                    ? proposal.changes.calendarStatus 
                    : (proposal.changes.calendarStatus as any)?.current || (proposal.changes.calendarStatus as any)?.proposed)
                }
                currentEditionYear={getEditionYear(proposal) ? parseInt(getEditionYear(proposal)!) : undefined}
                previousEditionYear={(proposal as any).previousEditionYear}
                previousCalendarStatus={(proposal as any).previousEditionCalendarStatus}
                previousEditionStartDate={(proposal as any).previousEditionStartDate}
              />
            )}
          </>
        )
      }}
    />
  )
}

export default EditionUpdateDetail
