// Enum types used by database
export enum AgentType {
  EXTRACTOR = 'EXTRACTOR',
  COMPARATOR = 'COMPARATOR',
  VALIDATOR = 'VALIDATOR',
  CLEANER = 'CLEANER',
  DUPLICATOR = 'DUPLICATOR',
  SPECIFIC_FIELD = 'SPECIFIC_FIELD'
}

export enum LogLevel {
  DEBUG = 'DEBUG',
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
}

export enum ProposalType {
  NEW_EVENT = 'NEW_EVENT',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EDITION_UPDATE = 'EDITION_UPDATE',
  RACE_UPDATE = 'RACE_UPDATE',
  EVENT_MERGE = 'EVENT_MERGE',
}
